import test from 'node:test';
import assert from 'node:assert/strict';
import {handleApi} from '../src/api.mjs';
import {localDatabase} from '../scripts/local-db.mjs';
const origin='https://community.example';
function harness(){const DB=localDatabase();const env={DB,MODERATOR_EMAIL:'alice@example.test'};async function call(user,path,method='GET',data,extra={}){const headers=user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{};if(method!=='GET')Object.assign(headers,{'Content-Type':'application/json','Origin':origin,'X-Common-Ground':'1'});Object.assign(headers,extra);const response=await handleApi(new Request(origin+'/api'+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)}),env);return {status:response.status,data:await response.json()};}async function join(user,group='neurodivergent'){const r=await call(user,'/profile','PUT',{name:user,group,role:'Student',university:'大学',language:'zh',consent:true});assert.equal(r.status,200);}async function connection(){await join('alice');await join('bob','neurotypical');await join('eve','neurotypical');const p=await call('alice','/questions','POST',{title:'如何安排小组作业？',body:'A clear plan would help.',topic:'Studying'});const o=await call('bob','/questions/'+p.data.id+'/offers','POST',{message:'We can plan together.'});const c=await call('alice','/offers/'+o.data.id+'/accept','POST',{});assert.equal(c.status,200);return {post:p.data.id,offer:o.data.id,conversation:c.data.conversationId};}return {DB,env,call,join,connection};}
test('anonymous visitors cannot read or write member data; identity needs both platform headers',async t=>{const h=harness();t.after(()=>h.DB.close());assert.equal((await h.call(null,'/questions')).status,401);assert.equal((await h.call(null,'/profile','PUT',{})).status,401);assert.equal((await h.call('alice','/me','GET',undefined,{'oai-authenticated-user-email':''})).data.signedIn,false);});
test('onboarding consent and input validation precede group participation',async t=>{const h=harness();t.after(()=>h.DB.close());assert.equal((await h.call('alice','/questions')).status,403);assert.equal((await h.call('alice','/profile','PUT',{consent:false})).data.error,'consentRequired');await h.join('alice');assert.equal((await h.call('alice','/profile','PUT',{name:'a',group:'admin',role:'Student',language:'en'})).status,400);assert.equal((await h.call('alice','/me')).data.profile.language,'zh');});
test('group permissions and cross-origin writes are enforced by the server',async t=>{const h=harness();t.after(()=>h.DB.close());await h.join('alice');await h.join('bob','neurotypical');const payload={title:'Question',body:'Context',topic:'Studying'};assert.equal((await h.call('bob','/questions','POST',payload)).status,403);assert.equal((await h.call('alice','/questions','POST',payload,{Origin:'https://other.example'})).status,403);const p=await h.call('alice','/questions','POST',payload);assert.equal((await h.call('alice','/questions/'+p.data.id+'/offers','POST',{message:'hello'})).status,403);});
test('an offer is private and only its author can accept; acceptance is idempotent',async t=>{const h=harness();t.after(()=>h.DB.close());const c=await h.connection();const outsider=await h.call('eve','/questions');assert.equal(outsider.data.questions[0].offers.length,0);assert.equal((await h.call('eve','/offers/'+c.offer+'/accept','POST',{})).status,404);assert.equal((await h.call('alice','/offers/'+c.offer+'/accept','POST',{})).data.conversationId,c.conversation);assert.equal((await h.call('bob','/conversations')).data.conversations.length,1);});
test('participants exchange persisted Chinese text and guide references; outsider has no message access',async t=>{const h=harness();t.after(()=>h.DB.close());const c=await h.connection();assert.equal((await h.call('alice','/conversations/'+c.conversation+'/messages','POST',{body:'我们用文字沟通吧。',guideId:'communication'})).status,201);const r=await h.call('bob','/conversations/'+c.conversation+'/messages');assert.equal(r.data.messages[0].body,'我们用文字沟通吧。');assert.equal(r.data.messages[0].guideId,'communication');assert.equal((await h.call('eve','/conversations/'+c.conversation+'/messages')).status,404);assert.equal((await h.call('eve','/conversations/'+c.conversation+'/messages','POST',{body:'intrusion'})).status,404);assert.equal((await h.call('eve','/conversations')).data.conversations.length,0);});
test('ending a connection stops both participants from sending while retaining history',async t=>{const h=harness();t.after(()=>h.DB.close());const c=await h.connection();await h.call('alice','/conversations/'+c.conversation+'/messages','POST',{body:'hello'});await h.call('bob','/conversations/'+c.conversation+'/end','POST',{});assert.equal((await h.call('alice','/conversations/'+c.conversation+'/messages','POST',{body:'more'})).status,409);assert.equal((await h.call('alice','/conversations/'+c.conversation+'/messages')).data.messages.length,1);});
test('blocking hides both parties and prevents messaging; unblock restores visibility',async t=>{const h=harness();t.after(()=>h.DB.close());const c=await h.connection();await h.call('bob','/blocks','POST',{userId:'alice'});assert.equal((await h.call('bob','/questions')).data.questions.length,0);assert.equal((await h.call('alice','/conversations')).data.conversations.length,0);assert.equal((await h.call('alice','/conversations/'+c.conversation+'/messages','POST',{body:'more'})).status,403);await h.call('bob','/blocks/alice','DELETE');assert.equal((await h.call('alice','/conversations')).data.conversations.length,1);});
test('reports can only be reviewed by the configured operator',async t=>{const h=harness();t.after(()=>h.DB.close());const c=await h.connection();assert.equal((await h.call('eve','/reports','POST',{conversationId:c.conversation,reason:'snoop'})).status,404);await h.call('bob','/reports','POST',{conversationId:c.conversation,reason:'A concern'});assert.equal((await h.call('bob','/reports')).status,403);const reports=(await h.call('alice','/reports')).data.reports;assert.equal(reports.length,1);assert.equal((await h.call('bob','/reports/'+reports[0].id)).status,403);assert.equal((await h.call('alice','/reports/'+reports[0].id)).status,200);await h.call('alice','/reports/'+reports[0].id+'/resolve','POST',{});assert.equal((await h.call('alice','/reports')).data.reports.length,0);});
test('burst posting is bounded and malformed requests preserve existing records',async t=>{const h=harness();t.after(()=>h.DB.close());await h.join('alice');for(let i=0;i<10;i++)assert.equal((await h.call('alice','/questions','POST',{title:'Question '+i,body:'Context',topic:'Studying'})).status,201);assert.equal((await h.call('alice','/questions','POST',{title:'Over limit',body:'Context',topic:'Studying'})).status,429);assert.equal((await h.call('alice','/questions')).data.questions.length,10);});
test('question pagination includes records with identical timestamps',async t=>{const h=harness();t.after(()=>h.DB.close());await h.join('alice');for(let i=0;i<60;i++)await h.DB.prepare('INSERT INTO posts(id,author_id,title,body,topic,created) VALUES(?,?,?,?,?,?)').bind(String(i).padStart(3,'0'),'alice','Question','Context','Studying',100).run();const first=(await h.call('alice','/questions')).data,last=first.questions.at(-1);const second=(await h.call('alice','/questions?before='+last.created+'&beforeId='+last.id)).data;assert.equal(first.questions.length,50);assert.equal(second.questions.length,10);assert.equal(new Set([...first.questions,...second.questions].map(q=>q.id)).size,60);});
