import test from 'node:test';
import assert from 'node:assert/strict';
import {zonedDateTimeToUtc,zonedDateTime,validTimeZone,agreementCalendar,agreementText,agreementPrintHTML} from '../public/group-agreements-export.js';
const agreement={id:'group-id',title:'共识小组 <script>alert(1)</script>',revision:3,roles:'各自选一个任务',meetingAgenda:'先看进度',communication:'文字',responseTime:'两天内',clarification:'请举例',breaks:'随时休息',members:[{id:'member',name:'小夏',confirmedRevision:3}],tasks:[{id:'task-id',text:'完成, 第一稿; 🐸\n再检查',assigneeId:'member',deadline:Date.UTC(2027,0,2,8),timeZone:'Asia/Shanghai'},{id:'no-date',text:'先想一想',assigneeId:null,deadline:null,timeZone:'Asia/Shanghai'}]};
test('explicit IANA zone conversions work independently of device time zone',()=>{assert.equal(zonedDateTimeToUtc('2027-01-02T16:00','Asia/Shanghai'),Date.UTC(2027,0,2,8));assert.equal(zonedDateTimeToUtc('2027-07-02T10:00','Europe/Amsterdam'),Date.UTC(2027,6,2,8));assert.equal(zonedDateTime(agreement.tasks[0].deadline,'Asia/Shanghai'),'2027-01-02T16:00');assert.equal(zonedDateTimeToUtc('','Asia/Shanghai'),null);assert.equal(validTimeZone('made/up'),false);});
test('invalid dates, spring clock gaps and ambiguous autumn clock times are rejected',()=>{assert.throws(()=>zonedDateTimeToUtc('2027-02-30T12:00','UTC'),/agreementsInvalidDeadline/);assert.throws(()=>zonedDateTimeToUtc('2027-01-01T24:00','UTC'),/agreementsInvalidDeadline/);assert.throws(()=>zonedDateTimeToUtc('2027-03-28T02:30','Europe/Amsterdam'),/agreementsInvalidDeadline/);assert.throws(()=>zonedDateTimeToUtc('2027-10-31T02:30','Europe/Amsterdam'),/agreementsAmbiguousDeadline/);assert.throws(()=>zonedDateTimeToUtc('2027-01-01T10:00','bad/zone'),/agreementsInvalidZone/);});
test('calendar exports only dated tasks as UTC with optional alerts and safe CRLF text',()=>{const ics=agreementCalendar(agreement,{language:'zh',now:Date.UTC(2026,9,4),remindMinutes:30});assert.equal(ics.match(/BEGIN:VEVENT/g).length,1);assert.ok(ics.includes('DTSTART:20270102T080000Z\r\n'));assert.ok(ics.includes('SEQUENCE:3\r\n'));assert.ok(ics.includes('TRIGGER:-PT30M\r\n'));assert.ok(ics.replace(/\r\n /g,'').includes('完成\\, 第一稿\\; 🐸\\n再检查'));assert.equal(agreementCalendar(agreement).includes('BEGIN:VALARM'),false);assert.throws(()=>agreementCalendar({...agreement,tasks:[]}),/agreementsNoDates/);for(const line of ics.split('\r\n'))assert.ok(Buffer.byteLength(line,'utf8')<=75);});
test('print export escapes user content, uses CSP-compatible external styles and contains no emails',()=>{const html=agreementPrintHTML(agreement,'zh'),text=agreementText(agreement,'zh');assert.equal(html.includes('<script>'),false);assert.equal(html.includes('<style>'),false);assert.ok(html.includes('href="/group-agreements.css"'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(text.includes('小夏 · 已阅读当前版本'));assert.ok(text.includes('Asia/Shanghai'));assert.equal(text.includes('member'),false);assert.equal(text.includes('@'),false);});
test('history previews omit current membership and confirmation roster',()=>{const text=agreementText({...agreement,revision:2},'zh',{includeMembers:false});assert.equal(text.includes('尚未阅读当前版本'),false);assert.equal(text.includes('组员\n'),false);assert.ok(text.includes('负责人: 小夏'));assert.ok(text.includes('版本: 2'));});
