// Small opt-in study rooms keep private goals separate from shared chat.
// Room messages are participant-visible and operator-accessible on reports;
// they are not encrypted private conversations or evidence of studying.
export const STUDY_ROOMS_SCHEMA=[
 "CREATE TABLE IF NOT EXISTS study_rooms (id TEXT PRIMARY KEY NOT NULL,host_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,title TEXT NOT NULL,language TEXT NOT NULL,duration_minutes INTEGER NOT NULL,starts_at INTEGER NOT NULL,ends_at INTEGER NOT NULL,state TEXT NOT NULL DEFAULT 'open',created INTEGER NOT NULL)",
 'CREATE INDEX IF NOT EXISTS study_rooms_created ON study_rooms(created,id)',
 "CREATE TABLE IF NOT EXISTS study_participants (room_id TEXT NOT NULL REFERENCES study_rooms(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,goal TEXT NOT NULL DEFAULT '',share_goal INTEGER NOT NULL DEFAULT 0,done INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'active',joined INTEGER NOT NULL,updated INTEGER NOT NULL,PRIMARY KEY(room_id,user_id))",
 'CREATE INDEX IF NOT EXISTS study_participants_user ON study_participants(user_id,room_id)',
 'CREATE TABLE IF NOT EXISTS study_messages (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,room_id TEXT NOT NULL REFERENCES study_rooms(id) ON DELETE CASCADE,author_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,body TEXT NOT NULL,created INTEGER NOT NULL)',
 'CREATE INDEX IF NOT EXISTS study_messages_room ON study_messages(room_id,id)',
 "CREATE TABLE IF NOT EXISTS study_reports (id TEXT PRIMARY KEY NOT NULL,reporter_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,room_id TEXT REFERENCES study_rooms(id) ON DELETE SET NULL,message_id INTEGER REFERENCES study_messages(id) ON DELETE SET NULL,target_kind TEXT NOT NULL,target_author_id TEXT REFERENCES profiles(id) ON DELETE SET NULL,room_title_snapshot TEXT NOT NULL,body_snapshot TEXT NOT NULL,reason TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',created INTEGER NOT NULL)",
 'CREATE INDEX IF NOT EXISTS study_reports_status ON study_reports(status,created,id)',
 'CREATE TABLE IF NOT EXISTS study_limits (user_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,bucket TEXT NOT NULL,period_start INTEGER NOT NULL,total INTEGER NOT NULL,PRIMARY KEY(user_id,bucket))'
];
const ready=new WeakMap();
export async function ensureStudyRoomsSchema(db){let task=ready.get(db);if(!task){task=(async()=>{for(const sql of STUDY_ROOMS_SCHEMA)await db.prepare(sql).run();})().catch(error=>{ready.delete(db);throw error;});ready.set(db,task);}await task;}
const DAY=86400000,HOUR=3600000,GRACE=15*60000;
export async function handleStudyRooms(request,url,id,ctx){
 const {db,body,text,fail,json,one,many,query,moderator=false}=ctx;await ensureStudyRoomsSchema(db);
 const path=url.pathname,method=request.method,now=Date.now();
 const only=(input,keys)=>{if(Object.keys(input).some(key=>!keys.includes(key)))fail(400,'invalidInput');};
 const cursor=value=>{if(value===null||value===undefined)return null;const number=Number(value);if(!Number.isSafeInteger(number)||number<0)fail(400,'invalidInput');return number;};
 async function rate(bucket,max,period=60000){const window=Math.floor(now/period),result=await query(db,'INSERT INTO study_limits(user_id,bucket,period_start,total) VALUES(?,?,?,1) ON CONFLICT(user_id,bucket) DO UPDATE SET period_start=excluded.period_start,total=CASE WHEN study_limits.period_start=excluded.period_start THEN study_limits.total+1 ELSE 1 END WHERE study_limits.period_start!=excluded.period_start OR study_limits.total<?',id,bucket,window,max).run();if(!result.meta.changes)fail(429,'tooFast');}
 const peerGuard=`NOT EXISTS(SELECT 1 FROM blocks b WHERE (b.blocker_id=? AND (b.blocked_id=r.host_id OR EXISTS(SELECT 1 FROM study_participants sp WHERE sp.room_id=r.id AND sp.status='active' AND sp.user_id=b.blocked_id))) OR (b.blocked_id=? AND (b.blocker_id=r.host_id OR EXISTS(SELECT 1 FROM study_participants sp WHERE sp.room_id=r.id AND sp.status='active' AND sp.user_id=b.blocker_id))))`;
 function summary(r){return {id:r.id,title:r.title,hostId:r.host_id,hostName:r.hostName,language:r.language,durationMinutes:r.duration_minutes,startsAt:r.starts_at,endsAt:r.ends_at,created:r.created,state:r.state==='open'&&r.ends_at>now?'open':'finished',participantCount:r.participantCount??0,mine:r.host_id===id,joined:!!r.isMember};}
 async function access(roomId,{participant=true,expired=false}={}){
  const room=await one(db,`SELECT r.*,p.name AS hostName,(SELECT COUNT(*) FROM study_participants sp WHERE sp.room_id=r.id AND sp.status='active') AS participantCount,EXISTS(SELECT 1 FROM study_participants sp WHERE sp.room_id=r.id AND sp.user_id=? AND sp.status='active') AS isMember,${peerGuard} AS accessible FROM study_rooms r JOIN profiles p ON p.id=r.host_id WHERE r.id=?`,id,id,id,roomId);
  if(!room||!room.accessible||participant&&!room.isMember)fail(404,'notFound');if(!expired&&now>=room.ends_at+GRACE)fail(410,'studyExpired');return room;
 }
 async function detail(roomId){const r=await access(roomId),rows=await many(db,"SELECT sp.*,p.name FROM study_participants sp JOIN profiles p ON p.id=sp.user_id WHERE sp.room_id=? AND sp.status='active' ORDER BY sp.joined,sp.user_id",roomId),own=rows.find(p=>p.user_id===id);return {room:summary(r),participants:rows.map(p=>({userId:p.user_id,name:p.name,joined:p.joined,sharedGoal:p.share_goal?p.goal:null,done:!!p.done,mine:p.user_id===id})),me:{goal:own?.goal??'',shareGoal:!!own?.share_goal,done:!!own?.done},serverNow:now};}
 function goal(input){only(input,['goal','shareGoal','shareConsent']);const value=text(input.goal??'',0,240),shared=input.shareGoal??false;if(typeof shared!=='boolean'||input.shareConsent!==undefined&&typeof input.shareConsent!=='boolean')fail(400,'invalidInput');if(shared&&input.shareConsent!==true)fail(400,'consentRequired');return {value,shared};}
 if(path==='/api/study-rooms'&&method==='GET'){
  const before=cursor(url.searchParams.get('before'))??Number.MAX_SAFE_INTEGER,beforeId=url.searchParams.get('beforeId')??'',lang=url.searchParams.get('language');if(lang!==null&&!['en','zh','either'].includes(lang))fail(400,'invalidInput');
  const rows=await many(db,`SELECT r.*,p.name AS hostName,(SELECT COUNT(*) FROM study_participants sp WHERE sp.room_id=r.id AND sp.status='active') AS participantCount,EXISTS(SELECT 1 FROM study_participants sp WHERE sp.room_id=r.id AND sp.user_id=? AND sp.status='active') AS isMember FROM study_rooms r JOIN profiles p ON p.id=r.host_id WHERE r.state='open' AND r.ends_at>? AND (r.created<? OR (r.created=? AND r.id<?)) AND ${peerGuard}${lang?" AND (r.language=? OR r.language='either')":''} ORDER BY r.created DESC,r.id DESC LIMIT 31`,id,now,before,before,beforeId,id,id,...(lang?[lang]:[]));
  return json({rooms:rows.slice(0,30).map(summary),hasMore:rows.length>30,serverNow:now});
 }
 if(path==='/api/study-rooms'&&method==='POST'){
  const input=await body(request);only(input,['title','language','durationMinutes']);const title=text(input.title,1,120);if(!['en','zh','either'].includes(input.language)||![15,25,45].includes(input.durationMinutes))fail(400,'invalidInput');
  await query(db,'DELETE FROM study_rooms WHERE created<?',now-7*DAY).run();await rate('write',30);await rate('createHour',3,HOUR);await rate('createDay',10,DAY);
  const roomId=crypto.randomUUID(),ends=now+input.durationMinutes*60000;
  const results=await db.batch([
   query(db,"INSERT INTO study_rooms(id,host_id,title,language,duration_minutes,starts_at,ends_at,created) SELECT ?,?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM study_rooms WHERE host_id=? AND state='open' AND ends_at>?) AND (SELECT COUNT(*) FROM study_rooms WHERE host_id=?)<30 AND (SELECT COUNT(*) FROM study_rooms)<500 AND (SELECT COUNT(*) FROM study_participants WHERE user_id=? AND status='active' AND room_id IN(SELECT id FROM study_rooms WHERE state='open' AND ends_at>?))<2",roomId,id,title,input.language,input.durationMinutes,now,ends,now,id,now,id,id,now),
   query(db,"INSERT INTO study_participants(room_id,user_id,joined,updated) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM study_rooms WHERE id=? AND host_id=?)",roomId,id,now,now,roomId,id)
  ]);if(!results[0].meta.changes)fail(409,'studyRoomLimit');return json(await detail(roomId),201);
 }
 let match=path.match(/^\/api\/study-rooms\/([^/]+)$/);
 if(match&&method==='GET')return json(await detail(match[1]));
 match=path.match(/^\/api\/study-rooms\/([^/]+)\/join$/);
 if(match&&method==='POST'){
  const input=goal(await body(request)),room=await access(match[1],{participant:false});if(room.state!=='open'||room.ends_at<=now)fail(410,'studyExpired');await rate('write',30);
  const prior=await one(db,'SELECT status FROM study_participants WHERE room_id=? AND user_id=?',room.id,id);if(prior?.status==='removed')fail(403,'studyRemoved');
  const result=await query(db,`INSERT INTO study_participants(room_id,user_id,goal,share_goal,joined,updated) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM study_rooms r WHERE r.id=? AND r.state='open' AND r.ends_at>? AND ${peerGuard}) AND ((SELECT COUNT(*) FROM study_participants WHERE room_id=? AND status='active')<8 OR EXISTS(SELECT 1 FROM study_participants WHERE room_id=? AND user_id=? AND status='active')) AND (SELECT COUNT(*) FROM study_participants WHERE user_id=? AND status='active' AND room_id IN(SELECT id FROM study_rooms WHERE state='open' AND ends_at>? AND id!=?))<2 ON CONFLICT(room_id,user_id) DO UPDATE SET goal=CASE WHEN study_participants.status='active' THEN study_participants.goal ELSE excluded.goal END,share_goal=CASE WHEN study_participants.status='active' THEN study_participants.share_goal ELSE excluded.share_goal END,status='active',joined=CASE WHEN study_participants.status='active' THEN study_participants.joined ELSE excluded.joined END,updated=excluded.updated WHERE study_participants.status!='removed'`,room.id,id,input.value,Number(input.shared),now,now,room.id,now,id,id,room.id,room.id,id,id,now,room.id).run();
  if(!result.meta.changes){await access(room.id,{participant:false});fail(409,'studyRoomFull');}return json(await detail(room.id));
 }
 match=path.match(/^\/api\/study-rooms\/([^/]+)\/leave$/);
 if(match&&method==='DELETE'){await rate('write',30);await db.batch([query(db,"UPDATE study_participants SET status='left',goal='',share_goal=0,updated=? WHERE room_id=? AND user_id=? AND status='active'",now,match[1],id),query(db,"UPDATE study_rooms SET state='closed',ends_at=MIN(ends_at,?) WHERE id=? AND host_id=?",now,match[1],id)]);return json({ok:true});}
 match=path.match(/^\/api\/study-rooms\/([^/]+)\/goal$/);
 if(match&&method==='PUT'){const value=goal(await body(request)),room=await access(match[1]);await rate('write',30);await query(db,"UPDATE study_participants SET goal=?,share_goal=?,updated=? WHERE room_id=? AND user_id=? AND status='active'",value.value,Number(value.shared),now,room.id,id).run();return json({me:{goal:value.value,shareGoal:value.shared},serverNow:now});}
 match=path.match(/^\/api\/study-rooms\/([^/]+)\/check-in$/);
 if(match&&method==='POST'){const input=await body(request);only(input,['done','publishConsent']);if(typeof input.done!=='boolean')fail(400,'invalidInput');if(input.publishConsent!==true)fail(400,'consentRequired');const room=await access(match[1]);await rate('write',30);await query(db,"UPDATE study_participants SET done=?,updated=? WHERE room_id=? AND user_id=? AND status='active'",Number(input.done),now,room.id,id).run();return json({done:input.done,serverNow:now});}
 match=path.match(/^\/api\/study-rooms\/([^/]+)\/end$/);
 if(match&&method==='POST'){await rate('write',30);const r=await query(db,"UPDATE study_rooms SET state='closed',ends_at=MIN(ends_at,?) WHERE id=? AND host_id=?",now,match[1],id).run();if(!r.meta.changes)fail(404,'notFound');return json({ok:true});}
 match=path.match(/^\/api\/study-rooms\/([^/]+)\/participants\/([^/]+)$/);
 if(match&&method==='DELETE'){let userId;try{userId=decodeURIComponent(match[2]);}catch{fail(400,'invalidInput');}if(userId===id)fail(400,'invalidInput');const room=await one(db,'SELECT id FROM study_rooms WHERE id=? AND host_id=?',match[1],id);if(!room)fail(404,'notFound');await rate('write',30);const r=await query(db,"UPDATE study_participants SET status='removed',goal='',share_goal=0,updated=? WHERE room_id=? AND user_id=? AND status='active'",now,room.id,userId).run();if(!r.meta.changes)fail(404,'notFound');return json({ok:true});}
 match=path.match(/^\/api\/study-rooms\/([^/]+)\/messages$/);
 if(match){const room=await access(match[1]);
  if(method==='GET'){const after=cursor(url.searchParams.get('after')),before=cursor(url.searchParams.get('before'));if(after!==null&&before!==null)fail(400,'invalidInput');const rows=await many(db,`SELECT m.id,m.author_id,m.body,m.created,p.name FROM study_messages m JOIN profiles p ON p.id=m.author_id WHERE m.room_id=? AND m.id${after!==null?'>':'<'}? AND NOT EXISTS(SELECT 1 FROM blocks b WHERE (b.blocker_id=? AND b.blocked_id=m.author_id) OR (b.blocker_id=m.author_id AND b.blocked_id=?)) ORDER BY m.id ${after!==null?'ASC':'DESC'} LIMIT 51`,room.id,after??before??Number.MAX_SAFE_INTEGER,id,id),selected=rows.slice(0,50);if(after===null)selected.reverse();return json({messages:selected.map(m=>({id:m.id,authorId:m.author_id,name:m.name,body:m.body,created:m.created,mine:m.author_id===id})),hasMore:rows.length>50,serverNow:now});}
  if(method==='POST'){if(room.state!=='open')fail(409,'studyEnded');const input=await body(request);only(input,['body','publishConsent']);if(input.publishConsent!==true)fail(400,'consentRequired');const content=text(input.body,1,2000);await rate('write',30);const r=await query(db,`INSERT INTO study_messages(room_id,author_id,body,created) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM study_rooms r JOIN study_participants own ON own.room_id=r.id WHERE r.id=? AND r.state='open' AND own.user_id=? AND own.status='active' AND r.ends_at+?>? AND ${peerGuard}) AND (SELECT COUNT(*) FROM study_messages WHERE room_id=?)<500`,room.id,id,content,now,room.id,id,GRACE,now,id,id,room.id).run();if(!r.meta.changes){await access(room.id);fail(409,'studyChatFull');}return json({id:r.meta.last_row_id},201);}
 }
 match=path.match(/^\/api\/study-rooms\/([^/]+)\/messages\/([^/]+)$/);
 if(match&&method==='DELETE'){const messageId=cursor(match[2]);await rate('write',30);const r=await query(db,'DELETE FROM study_messages WHERE id=? AND room_id=? AND author_id=?',messageId,match[1],id).run();if(!r.meta.changes)fail(404,'notFound');return json({ok:true});}
 match=path.match(/^\/api\/study-rooms\/([^/]+)(?:\/messages\/([^/]+))?\/reports$/);
 if(match&&method==='POST'){
  const input=await body(request);only(input,['reason']);const reason=text(input.reason,1,1000),room=await access(match[1],{participant:!!match[2]}),message=match[2]?await one(db,'SELECT id,author_id,body FROM study_messages WHERE id=? AND room_id=?',cursor(match[2]),room.id):null;if(match[2]&&!message)fail(404,'notFound');
  if(message&&await ctx.blocked(db,id,message.author_id))fail(404,'notFound');await rate('report',5);await query(db,"DELETE FROM study_reports WHERE status='resolved' AND created<?",now-30*DAY).run();const reportId=crypto.randomUUID();const r=await query(db,'INSERT INTO study_reports(id,reporter_id,room_id,message_id,target_kind,target_author_id,room_title_snapshot,body_snapshot,reason,created) SELECT ?,?,?,?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM study_reports)<5000',reportId,id,room.id,message?.id??null,message?'message':'room',message?.author_id??room.host_id,room.title,message?.body??room.title,reason,now).run();if(!r.meta.changes)fail(409,'studyReportLimit');return json({id:reportId},201);
 }
 if(path==='/api/study-reports'&&method==='GET'){if(!moderator)fail(403,'notAllowed');const rows=await many(db,"SELECT r.*,p.name AS authorName FROM study_reports r LEFT JOIN profiles p ON p.id=r.target_author_id WHERE r.status='open' ORDER BY r.created DESC,r.id DESC LIMIT 100");return json({reports:rows.map(r=>({id:r.id,roomId:r.room_id,messageId:r.message_id,targetKind:r.target_kind,authorName:r.authorName??'',roomTitle:r.room_title_snapshot,body:r.body_snapshot,reason:r.reason,created:r.created}))});}
 match=path.match(/^\/api\/study-reports\/([^/]+)\/resolve$/);
 if(match&&method==='POST'){if(!moderator)fail(403,'notAllowed');const report=await one(db,'SELECT * FROM study_reports WHERE id=?',match[1]);if(!report)fail(404,'notFound');const input=await body(request);only(input,['endRoom','removeMessage']);for(const key of ['endRoom','removeMessage'])if(input[key]!==undefined&&typeof input[key]!=='boolean')fail(400,'invalidInput');if(input.endRoom&&input.removeMessage||input.endRoom&&report.target_kind!=='room'||input.removeMessage&&report.target_kind!=='message')fail(400,'invalidInput');const statements=[query(db,"UPDATE study_reports SET status='resolved' WHERE id=?",report.id)];if(input.endRoom&&report.room_id)statements.unshift(query(db,"UPDATE study_rooms SET state='closed',ends_at=MIN(ends_at,?) WHERE id=?",now,report.room_id));if(input.removeMessage&&report.message_id)statements.unshift(query(db,'DELETE FROM study_messages WHERE id=? AND room_id=?',report.message_id,report.room_id));await db.batch(statements);return json({ok:true});}
 fail(404,'notFound');
}
